development: &default

  # Credentials for REST APIs
  client_id: AciEuAGllzOomt_6VLYosdp7jL1eRt1L-WjUkjlsZRZJpc1BDced1ny7kU-9ZR7zFDSYELRGqUMxMBUf
  client_secret: EIUPvBXIFYkHg6uyelXubh1k6nikP8JPVWqVQj6W2inIU1ZAXvPswDqrL9cLjRox_f_C_v4QX0fLkQYB

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: saigonyo360-facilitator_api1.gmail.com
  password: JF4TWBDRZLTXSM4H
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31ACVFsaASYEQHDjBfg.4AbXy73JwT
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: saigonyo360-facilitator@gmail.com 

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

test:
  <<: *default

production:
  <<: *default
  mode: live






